_posts/2015-08-26-making-an-impact-engineering-change.md
Hi, this is the blog post for #ILookLikeAnEngineer.  Time sensitive since their Indiegogo campagin ends in a little over a week.
=> Blog post promoting #ILookLikeAnEngineer

_config.yml, _includes/footer.html
Fixes #25.
Also update the copyright year while we're here.
=> Add "fork this page on github" text to footer.

index.html
=> Put mission statement on homepage.

index.html
Exactly what it says on the tin.
Screenshot: https://www.dropbox.com/s/825l2vjze0hm0n2/Screenshot%202016-02-19%2019.39.56.png?dl=0
Fixes #39.
=> Add link to Get Involved header

_includes/topbar.html
Fixes  #37 - Adds unlinked "What we do" to nested about section in nav bar.
=> Adding nested About section in top nav

about.html
This matches a little more the story that I tell, which explains the origins of the group a bit better, I think.
=> updated origin story

about.html
=> Update staff info

_includes/head.html, _includes/topbar.html, _layouts/default.html, _layouts/page.html, _layouts/post.html, _posts/2015-04-29-mobilebridgesf-ios-plangrid.md, _posts/2015-12-09-first-tenderloin-workshop.md, blog.md, index.html
This makes it so that the site works when previewed on another user's gh-pages branch.
This is important so that contributors are able to offer a preview of changes that they wish to merge.
=> Preface relative links (eg /images/foo/bar.png) with {{ site.github.url}}

history-and-where-we-are-now.md
=> link to first RailsBridge blog post

_includes/topbar.html
addressing issue - https://github.com/bridgefoundry/bridgefoundry.github.io/issues/67
@ultrasaurus Is the open source pairing night section that I turned into markdown a while ago ready to be a page? If so I Can add that in as a separate PR.
=> add How To to nav

index.html, site.css
We've gotten feedback that people don't feel like they can volunteer if they are coders -- nothing could be farther from the truth!  Here's an attempt to add some more welcoming language, along with a prettier "donate" button
=> nicer donate button and encourage more kinds of skills

open-source-workshops.md
added text from: https://github.com/bridgefoundry/organizing/issues/1
after review would be good to add to the "how to" menu
=> page for how to build community with open source workshop

README.md
Seems like it should be helpful.
Closes #88.
=> How to write a blog post in README.md

_posts/2017-12-20-the-real-magic-of-bridge-foundry.md
I've integrated the text that was in the PR into an actual markdown file in the _posts directory and checked it against a local deployment.
The only changes I've made was adding "*Post by Mary Jenn*" at the top because it seemed necessary based on how much the first two paragraphs used the "I" pronoun.
=> Add new post by Mary Jenn, 2012-12-20

_includes/head.html
=> add Google analytics

_posts/2018-01-08-the-real-magic-of-bridge-foundry.md
- fixed some small error: Ive => I've, inconsistent I/we
- adjusted language based to underscore premise of respecting everyone
=> a few edits to recent blog post

about.html, donate.md
=> Add hint for where to find EIN to /donate

_includes/footer.html, privacy_policy.md
What information is being collected?
Who is collecting it?
How is it collected?
Why is it being collected?
How will it be used?
Who will it be shared with?
What will be the effect of this on the individuals concerned?
Is the intended use likely to cause individuals to object or complain?
=> Adding privacy notice

about.md
=> Updating Board of Directors

_includes/topbar.html
=> How to links open to a new tab

.travis.yml, _posts/2020-01-07-call-for-proposal-research-plan.md
@iisa wrote first draft, review and edits with @mxie and Jéneen in meeting today
=> CFP for research plan and 2019 report

_layouts/default.html, _layouts/page.html, _layouts/post.html
So that we can get some analytics on our visitors.
=> Add Hubspot tracking code

job-description/exec-assistant.md
I think this is good to go now -- can someone proof-read?
----
when I run this locally, the markdown isn't converted into html
=> exec assistant job

about.md
=> Update about.md - Fix link to corporate docs

about.md
Kinsey on leave
Secretary => Desi
Sarah not on leave (also noted that I'm volunteering as CEO)
=> Update board member roles
